import Vue from 'vue';
import select from 'vue-select';
import InfiniteLoading from 'vue-infinite-loading';
import Multiselect from 'vue-multiselect';
import Datepicker from 'vuejs-datepicker';
import draggable from 'vuedraggable';
import VTooltip from 'v-tooltip';
import SpinnerLoaderComponent from '@components/shared/spinnerLoader';
import CustomSelect from '@components/form/fields/CustomSelect';
import CustomInput from '@components/form/fields/CustomInput';
import Notification from '@components/shared/notification';
import LeftSiderbar from '@components/shared/leftSidebar';
import RightSiderbar from '@components/shared/rightSidebar';
import Autocomplete from '@components/addressAutocomplete';
import Modal from '@components/modal';
import Sidetab from '@components/shared/leftSidebar/sideTabs';
import SidebarHistoryItem from '@components/shared/leftSidebar/historyItem';
import SidebarAdItem from '@components/shared/leftSidebar/adItem';
import SidebarApartmentItem from '@components/shared/leftSidebar/apartmentItem';
import AddressAutocomplete from '@components/addressAutocompleteNew';
import IncludeDataInRange from '@components/marketRadar/includeDataInRange';
import TransactionForm from '@components/form/transactionForm';
import PricePredictionBox from '@components/shared/pricePrediction/analyticsBox';
import StarRating from '@components/shared/starRating';
import BarChart from '@components/charts/barChart';
import Popover from '@components/shared/popover';
import VersionFooter from '@components/shared/versionFooter';

Vue.component('infiniteLoading', InfiniteLoading);
Vue.component('multiselect', Multiselect);
Vue.component('datepicker', Datepicker);
Vue.component('draggable', draggable);
Vue.component('vselect', select);
Vue.component('custom-select', CustomSelect);
Vue.component('v-popover', VTooltip.VPopover);
Vue.component('spinner-loader', SpinnerLoaderComponent);
Vue.component('custom-input', CustomInput);
Vue.component('notification', Notification);
Vue.component('left-sidebar', LeftSiderbar);
Vue.component('right-sidebar', RightSiderbar);
Vue.component('autocomplete', Autocomplete);
Vue.component('modal', Modal);
Vue.component('sidetab', Sidetab);
Vue.component('sidebar-history-item', SidebarHistoryItem);
Vue.component('sidebar-ad-item', SidebarAdItem);
Vue.component('sidebar-apartment-item', SidebarApartmentItem);
Vue.component('address-autocomplete', AddressAutocomplete);
Vue.component('include-data-in-range', IncludeDataInRange);
Vue.component('transaction-form', TransactionForm);
Vue.component('price-prediction-box', PricePredictionBox);
Vue.component('star-rating', StarRating);
Vue.component('custom-bar-chart', BarChart);
Vue.component('popover', Popover);
Vue.component('version-footer', VersionFooter);
